upgrade Pillow 10.4.0 → 11.2.1
The CI MinGW test job has begun failing:

  src/_webp.c:930:28: error: initialization of 'PyObject * (*)(PyObject *,
    PyObject *)' {aka 'struct _object * (*)(struct _object *,
    struct _object *)'} from incompatible pointer type 'PyObject * (*)(void)'
    {aka 'struct _object * (*)(void)'} [-Wincompatible-pointer-types]
    930 |     {"WebPDecoderVersion", WebPDecoderVersion_wrapper, METH_NOARGS, …
        |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
  src/_webp.c:930:28: note: (near initialization for 'webpMethods[4].ml_meth')
  src/_webp.c:887:1: note: 'WebPDecoderVersion_wrapper' declared here
    887 | WebPDecoderVersion_wrapper() {
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~
  src/_webp.c:932:6: error: initialization of 'PyObject * (*)(PyObject *,
    PyObject *)' {aka 'struct _object * (*)(struct _object *,
    struct _object *)'} from incompatible pointer type 'PyObject * (*)(void)'
    {aka 'struct _object * (*)(void)'} [-Wincompatible-pointer-types]
    932 |      WebPDecoderBuggyAlpha_wrapper,
        |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/_webp.c:932:6: note: (near initialization for 'webpMethods[5].ml_meth')
  src/_webp.c:915:1: note: 'WebPDecoderBuggyAlpha_wrapper' declared here
    915 | WebPDecoderBuggyAlpha_wrapper() {
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  building 'PIL._imagingtk' extension

  error: command 'C:\\msys64\\mingw64\\bin/gcc.EXE' failed with exit code 1

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow

Upgrading Pillow appears to be enough to resolve this issue. This drops support
for Python 3.8, which we no longer need now that Ubuntu 20.04 has dropped out of
support.

Gitlab: closes #2677