fix: Revert "common feasible_tree: C99 style"
This reverts commit 1b6234a82659edf445e89598ae9eddf6ae76f832. This commit
introduced some Undefined Behavior:

  lib/common/ns.c:594:21: error: variable 'heap' is used uninitialized whenever
    'if' condition is true [-Werror,-Wsometimes-uninitialized]
                  if (tree[subtree_count] == NULL) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  lib/common/ns.c:619:8: note: uninitialized use occurs here
    free(heap);
         ^~~~
  lib/common/ns.c:594:17: note: remove the 'if' if its condition is always false
                  if (tree[subtree_count] == NULL) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  lib/common/ns.c:603:3: note: variable 'heap' is declared here
    STheap_t *const heap = STbuildheap(tree,subtree_count);
    ^

In CI, surprisingly macOS+CMake was the only platform that caught this.

Reported-by: AppleClang 15.0.0.15000309 -Wsometimes-uninitialized