pointset: fix integers being accessed as doubles, causing ASan to detect stack overflow
9577eaf7c1908683b61662fe1c24d6af6230262f that changed point sets to use
floating-point points instead of integer points. It changed `cmppair` to
take its arguments as `pointf`s instead of `point`s, but didn't notice
that `intMPairDisc`, which is used by point maps that still use integer
points, also used `cmppair`.

Without this, with ASan enabled on 32-bit native Windows, six tests¹
failed in CI with errors like:
```
tests/test_regression.py::test_2241 =================================================================
==17660==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x04fff068 at pc 0x5f0675ba bp 0x04ffec5c sp 0x04ffec50
READ of size 8 at 0x04fff068 thread T0
    #0 0x5f0675b9 in cmppair C:\Users\magjac\graphviz\lib\common\pointset.c:36
    #1 0x6d88675c in dttree C:\Users\magjac\graphviz\lib\cdt\dttree.c:97
    #2 0x5f067387 in insertPM C:\Users\magjac\graphviz\lib\common\pointset.c:154
    #3 0x5ded540c in checkEdge C:\Users\magjac\graphviz\lib\neatogen\neatoinit.c:699
    #4 0x5ded589e in makeGraphData C:\Users\magjac\graphviz\lib\neatogen\neatoinit.c:839
    #5 0x5ded670b in majorization C:\Users\magjac\graphviz\lib\neatogen\neatoinit.c:1148
    #6 0x5ded76e4 in neatoLayout C:\Users\magjac\graphviz\lib\neatogen\neatoinit.c:1343
    #7 0x5ded1403 in neato_layout C:\Users\magjac\graphviz\lib\neatogen\neatoinit.c:1460
    #8 0x5f0ef273 in gvLayoutJobs C:\Users\magjac\graphviz\lib\gvc\gvlayout.c:84
    #9 0x00a51193 in main C:\Users\magjac\graphviz\cmd\dot\dot.c:72
    #10 0x00a527d2 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #11 0x00a526d9 in _scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #12 0x00a5257c in _scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #13 0x00a52837 in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #14 0x75e8fcc8  (C:\WINDOWS\System32\KERNEL32.DLL+0x6b81fcc8)
    #15 0x778b809d  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x4b2e809d)
    #16 0x778b806d  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x4b2e806d)

Address 0x04fff068 is located in stack of thread T0 at offset 32 in frame
    #0 0x5f06726f in insertPM C:\Users\magjac\graphviz\lib\common\pointset.c:147

  This frame has 1 object(s):
    [16, 36) 'dummy' <== Memory access at offset 32 partially overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp, SEH and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow C:\Users\magjac\graphviz\lib\common\pointset.c:36 in cmppair
Shadow bytes around the buggy address:
  0x04ffed80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x04ffee00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x04ffee80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x04ffef00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x04ffef80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x04fff000: 00 00 00 00 00 00 00 00 00 f1 f1 00 00[04]f3 f3
  0x04fff080: f3 f3 00 00 00 00 00 00 00 00 00 00 f1 f1 04 f2
  0x04fff100: 04 f2 f8 f3 f3 f3 f3 00 00 00 00 00 00 00 00 00
  0x04fff180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x04fff200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x04fff280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==17660==ABORTING
FAILED
```

¹ From a CI run:
```
=========================== short test summary info ===========================
FAILED tests/test_regression.py::test_1554 - subprocess.CalledProcessError: Command '['dot', '-Tsvg', WindowsPath('C:/GitLab-Runner/builds/magjac/graphviz/tests/1554.dot')]' returned non-zero exit status 1.
FAILED tests/test_regression.py::test_2241 - subprocess.CalledProcessError: Command '['dot', '-Tsvg', WindowsPath('C:/GitLab-Runner/builds/magjac/graphviz/tests/2241.dot')]' returned non-zero exit status 1.
FAILED tests/test_rtest.py::test_graph[overlap-input57-neato-gv-flags57] - Failed: Test overlap: == Layout failed ==
  dot -Kneato -Tgv -Goverlap=false -o ndata\overlap_neato_8bec687f3b1eb3e7ac33150ab5ff775438f1fc905f36df88f7e8ebf9237c3103.gv C:\GitLab-Runner\builds\magjac\graphviz\tests\graphs\overlap.gv
FAILED tests/test_rtest.py::test_graph[overlap-input58-neato-gv-flags58] - Failed: Test overlap: == Layout failed ==
  dot -Kneato -Tgv -Goverlap=scale -o ndata\overlap_neato_7fc7d43c1585a43a80a369e89d630ea50db93178d90a09bfdb5d3e82957eee91.gv C:\GitLab-Runner\builds\magjac\graphviz\tests\graphs\overlap.gv
FAILED tests/test_rtest.py::test_graph[neatosplines-input96-neato-gv-flags96] - Failed: Test neatosplines: == Layout failed ==
  dot -Kneato -Tgv -Goverlap=false -Gsplines -o ndata\neatosplines_neato_2b3620d8a4efdfdfcc8e1973a3729fb10d95c6a052c17e8cc3d76042dc984eef.gv C:\GitLab-Runner\builds\magjac\graphviz\tests\graphs\overlap.gv
FAILED tests/test_rtest.py::test_graph[neatosplines-input97-neato-gv-flags97] - Failed: Test neatosplines: == Layout failed ==
  dot -Kneato -Tgv -Goverlap=false -Gsplines=polyline -o ndata\neatosplines_neato_5838dcb42c3c8ea5b02216f98ad81864ba25f6901eb77379f6655f325e43cd36.gv C:\GitLab-Runner\builds\magjac\graphviz\tests\graphs\overlap.gv
= 6 failed, 699 passed, 34 skipped, 1 deselected, 144 xfailed, 4 xpassed in 1792.12s (0:29:52) =
```