gvc main: fix use of uninitialized 'len'
cppcheck observes:

  $ cppcheck -Ilib --check-level=exhaustive --force lib/gvc/gvdevice.c
  lib/gvc/gvdevice.c:475:56: error: Uninitialized variable: len [uninitvar]
          fprintf (stdout, "%g = %s %d\n", test[i], buf, len);
                                                         ^

This bug was introduced in 2d9043b35123a6e785c8ead127355fa58f42e9c2. There is no
changelog entry for this because this is in debug code.

Reported-by: cppcheck 2.17.1