gvc: add missing #include
This ensures `gvplugin_installed_t` is always in scope when referenced
in this header.

Without this change the next comit in this series, which clang-formats
gvusershape.c, would give errors like:

C:\Users\magjac\graphviz\lib\gvc\gvcint.h(65,2): error C2061: syntax error: identifier 'gvplugin_installed_t' [C:\Users\magjac\graphviz\build\lib\gvc\gvc.vcxproj]