gvmap: fix retention of stack pointer beyond its lifetime
cppcheck observes:

  $ cppcheck -Ilib --check-level=exhaustive --force cmd/gvmap/gvmap.c
  cmd/gvmap/gvmap.c:238:9: error: Address of local auto-variable assigned to a
    function parameter. [autoVariables]
          pm->opacity = stmp;
          ^

This bug was introduced in a889d69258763de3dcaf267e584204eefcbb7fd3. No
adjustment needs to be made to follow on code because `opacity` is only ever
used as `if (opacity && strlen(opacity) >= 2) …`.

Reported-by: cppcheck 2.17.1