expr: squash macOS compilation warning
The macOS+CMake job has begun failing with:

    [ 29%] Building C object lib/expr/CMakeFiles/expr.dir/exeval.c.o
    /Users/gitlab/builds/graphviz/graphviz/lib/expr/exeval.c:1337:8: error: variable 'v' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
                            if (ex->disc->lengthf != NULL) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/gitlab/builds/graphviz/graphviz/lib/expr/exeval.c:1345:10: note: uninitialized use occurs here
                    return v;
                           ^
    /Users/gitlab/builds/graphviz/graphviz/lib/expr/exeval.c:1337:4: note: remove the 'if' if its condition is always true
                            if (ex->disc->lengthf != NULL) {
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/gitlab/builds/graphviz/graphviz/lib/expr/exeval.c:1056:2: note: variable 'v' is declared here
            Extype_t                v;
            ^

This problem was introduced in 7aaad845457e1f8c93ae07fa0a0ee4961f4242e6.

Gitlab: fixes #2680