smyrna: Add libGLU and libGL as libraries to link to which was missing
Fixes this error:
[   67s] libtool: link: gcc -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -ffast-math -fno-strict-aliasing -fno-strict-overflow -fPIC -I/usr/include/ruby-3.4.0 -fpermissive -Wall -Wextra -Wmissing-include-dirs -Wswitch-default -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wconversion -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wstrict-prototypes -Wpointer-arith -Wall -pie -o .libs/smyrna arcball.o draw.o glexpose.o glmotion.o gltemplate.o gui/appmouse.o gui/callbacks.o gvprpipe.o hier.o hotkeymap.o main.o polytess.o selectionfuncs.o smyrna_utils.o topfisheyeview.o topviewfuncs.o tvnodes.o viewport.o viewportcamera.o gui/datalistcallbacks.o gui/frmobjectui.o gui/glcompui.o gui/gui.o gui/menucallbacks.o gui/toolboxcallbacks.o gui/topviewsettings.o glutrender.o -Wl,--export-dynamic  ../../lib/topfish/.libs/libtopfish_C.a ../../lib/gvpr/.libs/libgvpr_C.a ../../lib/neatogen/.libs/libneatogen_C.a ../../lib/expr/.libs/libexpr_C.a /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/lib/cdt/.libs/libcdt.so ../../lib/common/.libs/libcommon_C.a ../../lib/glcomp/.libs/libglcomp_C.a ../../lib/gvc/.libs/libgvc_C.a /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/lib/xdot/.libs/libxdot.so /usr/lib64/libltdl.so -lz ../../lib/pathplan/.libs/libpathplan_C.a ../../lib/xdot/.libs/libxdot_C.a ../../lib/cgraph/.libs/libcgraph_C.a ../../lib/cdt/.libs/libcdt_C.a ../../lib/util/.libs/libutil_C.a -lglut -lgtkglext-x11-1.0 -lgdkglext-x11-1.0 -lGL -lglade-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lharfbuzz -lfontconfig -lfreetype -lxml2 -lexpat -lgts -lgthread-2.0 -lgmodule-2.0 -lglib-2.0 -lm -pthread -Wl,-rpath -Wl,/usr/lib64
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o: in function `drawTessPolygon':
[   70s] /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:76:(.text+0x2f5b): undefined reference to `gluTessProperty'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:96:(.text+0x2f66): undefined reference to `gluTessBeginPolygon'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:104:(.text+0x2f6f): undefined reference to `gluTessBeginContour'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:90:(.text+0x3016): undefined reference to `gluTessVertex'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:108:(.text+0x302c): undefined reference to `gluTessEndContour'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:64:(.text+0x3051): undefined reference to `gluNewTess'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:66:(.text+0x3068): undefined reference to `gluTessCallback'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:67:(.text+0x307c): undefined reference to `gluTessCallback'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:68:(.text+0x3090): undefined reference to `gluTessCallback'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:69:(.text+0x30a4): undefined reference to `gluTessCallback'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o: in function `glexpose_main':
[   70s] /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/glexpose.c:59:(.text+0x8108): undefined reference to `gluSphere'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/glexpose.c:34:(.text+0x82c7): undefined reference to `gluNewQuadric'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/glexpose.c:35:(.text+0x82db): undefined reference to `gluQuadricNormals'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/glexpose.c:36:(.text+0x82ec): undefined reference to `gluQuadricDrawStyle'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans0.ltrans.o: in function `drawTessPolygon':
[   70s] /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/polytess.c:100:(.text+0x3043): undefined reference to `gluTessEndPolygon'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans10.ltrans.o: in function `GetOGLPosRef':
[   70s] /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/../../lib/glcomp/glutils.c:38:(.text+0x19fc): undefined reference to `gluProject'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/../../lib/glcomp/glutils.c:42:(.text+0x1a4d): undefined reference to `gluUnProject'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans10.ltrans.o: in function `GetOGLDistance':
[   70s] /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/../../lib/glcomp/glutils.c:68:(.text+0x1b77): undefined reference to `gluProject'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/../../lib/glcomp/glutils.c:74:(.text+0x1bc2): undefined reference to `gluUnProject'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/../../lib/glcomp/glutils.c:79:(.text+0x1c1b): undefined reference to `gluUnProject'
[   70s] /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/ccnxwVAu.ltrans10.ltrans.o: in function `to3D':
[   70s] /home/abuild/rpmbuild/BUILD/graphviz-addons-14.1.2-build/graphviz-14.1.2/cmd/smyrna/../../lib/glcomp/glutils.c:118:(.text+0x1d89): undefined reference to `gluUnProject'
[   70s] collect2: error: ld returned 1 exit status