tests: fix 'is_asan_instrumented' on Windows
The prior implementation didn't work because (1) "It isn't possible to
create an EXE or DLL that contains debug information. Debug information
is always placed in an OBJ or PDB file."¹, (2) The `__asan_init`
symbol is not present in the `dot.obj` file either² and (3) There seems
to be no other way to produce the "__asan_init" text from `dot.exe`
using `dumpbin`³.

Without this change, with ASan enabled, test_2599 failed with:
```
tests/test_regression.py::test_2599 Mingle params:
  outer_iter = 4
  method = 1
  compatibility_method = 1
  K = -1
  fmt = gv
  nneighbors = 10
  max_recursion = 100
  angle_param = -1
  angle = 40
Process graph %1 in file <stdin>
n = 5 nz = 10
=================================================================
==8660==ERROR: AddressSanitizer: access-violation on unknown address 0x0000000001e4 (pc 0x000180010027 bp 0x00bd820fed40 sp 0x00bd820fec90 T0)
==8660==The signal is caused by a READ memory access.
==8660==Hint: address points to the zero page.
    #0 0x000180010026  (C:\Users\magjac\graphviz\build\_CPack_Packages\win64\NSIS\Graphviz-13.0.0~dev.20250201.0959-win64\bin\ANN.dll+0x180010026)
    #1 0x7ff7061fb983 in nearest_neighbor_graph_ann(int, int, class std::vector<double, class std::allocator<double>> const &, int &, class std::vector<int, class std::allocator<int>> &, class std::vector<int, class std::allocator<int>> &, class std::vector<double, class std::allocator<double>> &) C:\Users\magjac\graphviz\lib\mingle\nearest_neighbor_graph_ann.cpp:99
    #2 0x7ff7061d61fd in nearest_neighbor_graph(int, int, class std::vector<double, class std::allocator<double>> const &) C:\Users\magjac\graphviz\lib\mingle\nearest_neighbor_graph.cpp:36
    #3 0x7ff7061a6d99 in bundle C:\Users\magjac\graphviz\cmd\mingle\minglemain.cpp:439
    #4 0x7ff7061a738f in main C:\Users\magjac\graphviz\cmd\mingle\minglemain.cpp:477
    #5 0x7ff706228d78 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #6 0x7ff706228cc1 in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #7 0x7ff706228b7d in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #8 0x7ff706228ded in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #9 0x7ffd88157373  (C:\WINDOWS\System32\KERNEL32.DLL+0x180017373)
    #10 0x7ffd8a17cc90  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18004cc90)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: access-violation (C:\Users\magjac\graphviz\build\_CPack_Packages\win64\NSIS\Graphviz-13.0.0~dev.20250201.0959-win64\bin\ANN.dll+0x180010026)
==8660==ABORTING
FAILED

================================== FAILURES ===================================
__________________________________ test_2599 __________________________________
[XPASS(strict)] https://gitlab.com/graphviz/graphviz/-/issues/2599
----------- generated xml file: C:\Users\magjac\graphviz\report.xml -----------
=========================== short test summary info ===========================
FAILED tests/test_regression.py::test_2599
====================== 1 failed, 321 deselected in 6.83s ======================
```

¹ https://learn.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=msvc-170
² `dumpbin -symbols dot.obj | grep -i asan` produces:
        01B 00000000 UNDEF  notype ()    External     | __asan_report_store4
        031 00000000 UNDEF  notype       External     | __asan_shadow_memory_dynamic_address
        034 00000000 SECT9  notype       Static       | L___asan_gen_.0
        035 00000008 SECT9  notype       Static       | L___asan_gen_.1
        036 0000000C SECT9  notype       Static       | L___asan_gen_.2
        039 00000040 SECTA  notype       Static       | L__asan_global_Gvc
        03A 0000001C SECT9  notype       Static       | L___asan_gen_.3
        03B 00000020 SECT9  notype       Static       | L___asan_gen_.4
        03C 00000000 SECTA  notype       Static       | L__asan_global_G
³ Even `dumpbin -all` does not produce the text `__asan_init`. The
closest is `dumpbin -imports dot.exe | grep -i asan` which produces:
        10 __asan_default_options__dll
        11 __asan_default_suppressions__dll
        52 __asan_on_error__dll
        96 __asan_should_detect_stack_use_after_return
        33 __asan_get_shadow_memory_dynamic_address
        87 __asan_set_seh_filter
        5D __asan_register_globals
        CA __asan_unregister_globals
        7F __asan_report_store4
        2F __asan_get_report_description
        86 __asan_set_error_report_callback