vpsc: fix: throw 'runtime_error's instead of C strings
cppcheck notices that one of these instances threw a dangling pointer:

  $ cppcheck -Ilib --check-level=exhaustive --force lib/vpsc/solve_VPSC.cpp
  Checking lib/vpsc/solve_VPSC.cpp ...
  lib/vpsc/solve_VPSC.cpp:206:23: error: Returning object that will be invalid
    when returning. [returnDanglingLifetime]
    throw s.str().c_str();
                       ^
  lib/vpsc/solve_VPSC.cpp:206:23: note: Pointer to container is created here.
    throw s.str().c_str();
                       ^
  lib/vpsc/solve_VPSC.cpp:206:23: note: Returning object that will be invalid
    when returning.
    throw s.str().c_str();
                       ^

This change switches to the recommended practice of throwing by value and
throwing an actual exception type.

Reported-by: cppcheck 2.17.1