CMake dot: use a larger stack when compiled with ASan on Windows
Without this change, with ASan enabled, test_long_chain failed in CI¹ with:
```
================================== FAILURES ===================================
_______________________________ test_long_chain _______________________________

    def test_long_chain():
        """
        This test will fail on 32bit Windows machine if compiled with stack size < 16MB.
        long_chain input file generated using code below:
          from graphviz import Digraph

          graph = Digraph(format="svg")

          prev = "start"
          graph.node("start", label="start")

          for i in range(33000):
            new_node = str(i)
            graph.node(new_node, label=new_node, shape="rectangle")

            graph.edge(prev, new_node)

            prev = new_node

          graph.render("long_chain")
        """
>       subprocess.check_call(
            ["dot", "-Tsvg", "-o", os.devnull, Path(__file__).parent / "long_chain"]
        )

tests\regression_tests\large\test_large_graphs.py:35:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['dot', '-Tsvg', '-o', 'nul', WindowsPath('C:/GitLab-Runner/builds/magjac/graphviz/tests/regression_tests/large/long_chain')],)
kwargs = {}, retcode = 3221225477
cmd = ['dot', '-Tsvg', '-o', 'nul', WindowsPath('C:/GitLab-Runner/builds/magjac/graphviz/tests/regression_tests/large/long_chain')]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the call function.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['dot', '-Tsvg', '-o', 'nul', WindowsPath('C:/GitLab-Runner/builds/magjac/graphviz/tests/regression_tests/large/long_chain')]' returned non-zero exit status 3221225477.

C:\python\tools\Lib\subprocess.py:419: CalledProcessError
---------------------------- Captured stderr call -----------------------------
=================================================================
==2216==ERROR: AddressSanitizer: stack-overflow on address 0x7ff8796a3a28 (pc 0x7ff8796a3a28 bp 0x000000000000 sp 0x00d689403f90 T0)
--- generated xml file: C:\GitLab-Runner\builds\magjac\graphviz\report.xml ----
=========================== short test summary info ===========================
FAILED tests/regression_tests/large/test_large_graphs.py::test_long_chain - subprocess.CalledProcessError: Command '['dot', '-Tsvg', '-o', 'nul', WindowsPath('C:/GitLab-Runner/builds/magjac/graphviz/tests/regression_tests/large/long_chain')]' returned non-zero exit status 3221225477.
= 1 failed, 704 passed, 34 skipped, 1 deselected, 144 xfailed, 4 xpassed in 2961.60s (0:49:21) =
```

¹ For unknown reasons, this test passed locally with the original stack
size, but failed in the same way with half the original stack.