gvpr: fix -Wsometimes-uninitialized warning on macOS
101abbda84e49daddb44b6d788159a60b0747463 introduced a new compilation warning
that is failing the macOS CMake build in CI:

    /Users/gitlab/builds/graphviz/graphviz/lib/gvpr/compile.c:1426:11: error:
      variable 'v' is used uninitialized whenever 'if' condition is true
      [-Werror,-Wsometimes-uninitialized]
          if (getArg(args[0].integer, state, &arg) != 0) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/gitlab/builds/graphviz/graphviz/lib/gvpr/compile.c:1439:12: note:
      uninitialized use occurs here
        return v;
               ^
    /Users/gitlab/builds/graphviz/graphviz/lib/gvpr/compile.c:1426:7: note:
      remove the 'if' if its condition is always false
          if (getArg(args[0].integer, state, &arg) != 0) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/gitlab/builds/graphviz/graphviz/lib/gvpr/compile.c:565:3: note:
      variable 'v' is declared here
      Extype_t v;
      ^