fdpgen pswrite: fix use of uninitialized 'portColor'
cppcheck observes:

  $ cppcheck -Ilib --check-level=exhaustive --force lib/fdpgen/dbg.c
  lib/fdpgen/dbg.c:318:8: error: Uninitialized variable: portColor
    [legacyUninitvar]
    if (!portColor) {
         ^

No changelog entry is added for this because it is in `DEBUG`-guarded code.

Reported-by: cppcheck 2.17.1