CMake: enable -Wmissing-initialized
Following the prior series, Graphviz builds warning-free with this enabled.

This requires disabling -Werror for this on MinGW because the compiler there
seems to have an unsophisticated interpretation of this where it treats any
uninitialized union member as if the entire union were uninitialized:

  lib/gvpr/compile.c: In function 'getval':
  lib/gvpr/compile.c:1477:12: error: 'v.integer' may be used uninitialized
    [-Werror=maybe-uninitialized]
   1477 |     return v;
        |            ^
  lib/gvpr/compile.c:623:12: note: 'v.integer' was declared here
    623 |   Extype_t v;
        |            ^