gvpr: fix compilation on Solaris
Compilation on Solaris fails due to symbol conflicts:

  In file included from /builds/graphviz/graphviz-14.1.1/lib/gvpr/gvpr.c:25:
  /builds/graphviz/graphviz-14.1.1/lib/gvpr/compile.h:41:3: error: conflicting
    types for 'lock_t'; have 'struct <anonymous>'
     41 | } lock_t;
        |   ^~~~~~
  In file included from /usr/include/sys/machtypes.h:12,
                   from /usr/include/sys/types.h:17,
                   from /usr/include/string.h:15,
                   from /builds/graphviz/graphviz-14.1.1/lib/cdt/cdt.h:27,
                   from /builds/graphviz/graphviz-14.1.1/lib/cgraph/cgraph.h:32,
                   from /builds/graphviz/graphviz-14.1.1/lib/gvpr/gvpr.c:20:
  /usr/include/ia32/sys/machtypes.h:50:25: note: previous declaration of
    'lock_t' with type 'lock_t' {aka 'unsigned int'}
     50 | typedef unsigned int    lock_t;         /* lock work for busy wait *

Gitlab: fixes #2802
Reported-by: Jakub Kulik
Suggested-by: Jakub Kulik