CI: upgrade macOS, macOS 13 (Ventura) + Xcode 14 → macOS 14 (Sonoma) + Xcode 15
macOS jobs have begun failing in CI:

  ERROR: The "macos-13-xcode-14" image is not present on list of allowed images:
  - macos-14-xcode-15
  - macos-15-xcode-16
  Please check runner's allowed_images configuration:
    https://docs.gitlab.com/runner/configuration/advanced-configuration.html

It seems the macos-13-xcode-14 image has dropped out of support.¹ In future
perhaps the specific image should be removed entirely from these definitions,
leaving the jobs to run on the latest GA image:²

  If no image is specified, the macOS runner uses `macos-14-xcode-15`.

This change does not fully solve macOS CI problems, because upgrading causes a
number of test cases to fail. But it at least gets CI to the point where it is
checking Graphviz builds OK on macOS.

¹ https://gitlab.com/gitlab-org/gitlab/-/commit/d19f91889b4e237c18b188ef31a659ae7a98e529
² https://docs.gitlab.com/ci/runners/hosted_runners/macos/

Gitlab: #2667